# Generated by Django 4.1 on 2023-09-05 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dsh_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dsh_email', models.EmailField(default='email@gmail.com', max_length=255)),
                ('dsh_phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('dsh_image', models.FileField(default='', upload_to='profiles')),
                ('dsh_username', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dsh_password', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('dsh_date', models.DateField(auto_now_add=True, null=True)),
                ('active_status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('dpt_Status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empdesignation', models.CharField(default='', max_length=255)),
                ('empfullName', models.CharField(max_length=255)),
                ('empidreg', models.CharField(default='', max_length=200)),
                ('empstate', models.CharField(default='', max_length=200)),
                ('empPhone', models.CharField(max_length=15)),
                ('empemail', models.EmailField(max_length=254)),
                ('empdofj', models.DateField(null=True)),
                ('empconfirmsalary', models.IntegerField(default=0, null=True)),
                ('empfirst_salry', models.IntegerField(default=0)),
                ('emptol_salary', models.IntegerField(default=0)),
                ('emp_salary_status', models.IntegerField(default=0)),
                ('emp_status', models.IntegerField(default=0)),
                ('acc_dashid', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.dashboard_register')),
                ('empdept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_fullname', models.CharField(max_length=255)),
                ('auth_signature', models.FileField(default='', upload_to='Receipt')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('company_address1', models.CharField(default='', max_length=200)),
                ('company_address2', models.CharField(default='', max_length=200)),
                ('company_address3', models.CharField(default='', max_length=200)),
                ('company_logo', models.FileField(default='', upload_to='Receipt')),
                ('company_seal', models.FileField(default='', upload_to='Receipt')),
                ('company_email', models.CharField(default='', max_length=200)),
                ('company_site', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Register_State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_id', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('state_status', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('allocate_status', models.CharField(blank=True, default='0', max_length=255, null=True)),
                ('allocate_dash', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.dashboard_register')),
                ('allocateid', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.employeeregister')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('dofj', models.DateField()),
                ('next_pay_date', models.DateField(null=True)),
                ('next_pat_amt', models.IntegerField(default=0)),
                ('refrence', models.CharField(max_length=255)),
                ('firstpay_id', models.IntegerField(default=0)),
                ('fixed_intial_amt', models.IntegerField(default=0)),
                ('regbalance_amt', models.IntegerField(default=0)),
                ('reg_payedtotal', models.IntegerField(default=0)),
                ('regtotal_amt', models.IntegerField(default=0)),
                ('reg_status', models.IntegerField(default=0)),
                ('payprogress', models.IntegerField(default=10)),
                ('payment_status', models.IntegerField(default=0)),
                ('dept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.department')),
                ('reg_state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydofj', models.DateField(null=True)),
                ('head_name', models.CharField(default='', max_length=255)),
                ('payintial_amt', models.IntegerField(default=0)),
                ('paybalance_amt', models.IntegerField(default=0)),
                ('paytotal_amt', models.IntegerField(default=0)),
                ('pay_status', models.IntegerField(default=0)),
                ('admin_payconfirm', models.IntegerField(default=0)),
                ('pay_state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state')),
                ('reg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeExpence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exin_head_name', models.CharField(max_length=255)),
                ('exin_date', models.DateField(null=True)),
                ('exin_amount', models.IntegerField(default=0, null=True)),
                ('exin_typ', models.IntegerField(default=0)),
                ('exin_dese', models.TextField(default='')),
                ('exin_status', models.IntegerField(default=0)),
                ('exin_state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state')),
            ],
        ),
        migrations.CreateModel(
            name='FixedExpence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_head_name', models.CharField(max_length=255)),
                ('fixed_date', models.DateField(null=True)),
                ('fixed_amount', models.IntegerField(default=0)),
                ('fixed_typ', models.IntegerField(default=0)),
                ('fixed_dese', models.TextField(default='')),
                ('fixed_status', models.IntegerField(default=0)),
                ('fixed_state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empsalary_month', models.CharField(default='', max_length=55)),
                ('empslaray_date', models.DateField(null=True)),
                ('emppaid_amt', models.IntegerField(default=0)),
                ('empfull_leave', models.IntegerField(default=0)),
                ('emphalf_leave', models.IntegerField(default=0)),
                ('empfull_leave_amt', models.IntegerField(default=0)),
                ('emphalf_leave_amt', models.IntegerField(default=0)),
                ('emp_delay', models.IntegerField(default=0)),
                ('emp_delay_amt', models.IntegerField(default=0)),
                ('emp_othe_head', models.CharField(default='', max_length=100)),
                ('emp_other_amt', models.IntegerField(default=0)),
                ('emp_other_damt', models.IntegerField(default=0)),
                ('emp_paidstatus', models.IntegerField(default=0)),
                ('empreg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.employeeregister')),
            ],
        ),
        migrations.CreateModel(
            name='Company_Holidays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ch_sdate', models.DateField(null=True)),
                ('ch_edate', models.DateField(null=True)),
                ('ch_no', models.IntegerField(default=0, null=True)),
                ('ch_workno', models.IntegerField(default=0, null=True)),
                ('ch_state', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state')),
            ],
        ),
    ]
