# Generated by Django 4.1 on 2023-02-15 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='head_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='register',
            name='firstpay_id',
            field=models.IntegerField(default=0),
        ),
    ]
