# Generated by Django 4.1 on 2023-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_paymenthistory_head_name_register_firstpay_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='intial_amt',
            new_name='payintial_amt',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='total_amt',
            new_name='paytotal_amt',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='dofj',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='paydofj',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
