# Generated by Django 4.1 on 2023-02-15 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0003_rename_intial_amt_paymenthistory_payintial_amt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='reg_id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dept_id',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='PaymentHistory',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
