# Generated by Django 4.1 on 2023-02-15 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_app', '0004_remove_paymenthistory_reg_id_remove_register_dept_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=255)),
                ('dpt_Status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=15)),
                ('dofj', models.DateField()),
                ('refrence', models.CharField(max_length=255)),
                ('firstpay_id', models.IntegerField(default=0)),
                ('reg_status', models.IntegerField(default=0)),
                ('dept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paydofj', models.DateField(auto_now_add=True, null=True)),
                ('head_name', models.CharField(default='', max_length=255)),
                ('payintial_amt', models.IntegerField(default=0)),
                ('paytotal_amt', models.IntegerField(default=0)),
                ('pay_status', models.IntegerField(default=0)),
                ('reg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register')),
            ],
        ),
    ]
