# Generated by Django 4.1 on 2023-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='paybalance_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='regbalance_amt',
            field=models.IntegerField(default=0),
        ),
    ]
