# Generated by Django 4.1 on 2023-02-16 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0006_paymenthistory_paybalance_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='admin_payconfirm',
            field=models.IntegerField(default=0),
        ),
    ]
