# Generated by Django 4.1 on 2023-02-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0007_paymenthistory_admin_payconfirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='payment_status',
            field=models.IntegerField(default=0),
        ),
    ]
