# Generated by Django 4.1 on 2023-02-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0009_register_regtotal_amt'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='payprogress',
            field=models.IntegerField(default=0),
        ),
    ]
