# Generated by Django 4.1 on 2023-02-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0011_alter_register_payprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='next_pay_date',
            field=models.DateField(null=True),
        ),
    ]
