# Generated by Django 4.1 on 2023-02-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0012_register_next_pay_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='paydofj',
            field=models.DateField(null=True),
        ),
    ]
