# Generated by Django 4.1 on 2023-02-21 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0013_alter_paymenthistory_paydofj'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='next_pat_amt',
            field=models.IntegerField(default=0),
        ),
    ]
