# Generated by Django 4.1 on 2023-02-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0015_register_reg_payedtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dpt_Status',
            field=models.IntegerField(default=0, max_length=50),
        ),
    ]
