# Generated by Django 4.1 on 2023-02-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0016_alter_department_dpt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dpt_Status',
            field=models.IntegerField(default=0),
        ),
    ]
