# Generated by Django 4.1 on 2023-02-25 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0017_alter_department_dpt_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empdesignation', models.CharField(default='', max_length=255)),
                ('empfullName', models.CharField(max_length=255)),
                ('empidreg', models.CharField(default='', max_length=200)),
                ('empPhone', models.CharField(max_length=15)),
                ('empemail', models.EmailField(max_length=254)),
                ('empdofj', models.DateField(null=True)),
                ('empconfirmsalary', models.IntegerField(default=0)),
                ('emp_status', models.IntegerField(default=0)),
                ('empdept_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empsalary_month', models.CharField(max_length=55)),
                ('empslaray_date', models.DateField(null=True)),
                ('emppaid_amt', models.IntegerField(default=0)),
                ('emp_paidstatus', models.IntegerField(default=0)),
                ('empreg_id', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.employeeregister')),
            ],
        ),
    ]
