# Generated by Django 4.1 on 2023-02-25 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0018_employeeregister_employeesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeregister',
            name='empfirst_salry',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeeregister',
            name='emptol_salary',
            field=models.IntegerField(default=0),
        ),
    ]
