# Generated by Django 4.1 on 2023-02-25 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0019_employeeregister_empfirst_salry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='empsalary_month',
            field=models.CharField(default='', max_length=55),
        ),
    ]
