# Generated by Django 4.1 on 2023-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0021_employeeregister_emp_salary_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expence_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_head_name', models.CharField(max_length=255)),
                ('exp_date', models.DateField(null=True)),
                ('exp_amount', models.IntegerField(default=0)),
                ('exp_typ', models.CharField(default='', max_length=200)),
                ('exp_dese', models.TextField(default='')),
                ('exp_status', models.IntegerField(default=0)),
            ],
        ),
    ]
