# Generated by Django 4.1 on 2023-02-26 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0022_expence_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedExpence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_head_name', models.CharField(max_length=255)),
                ('fixed_date', models.DateField(null=True)),
                ('fixed_amount', models.IntegerField(default=0)),
                ('fixed_typ', models.IntegerField(default=0)),
                ('fixed_dese', models.TextField(default='')),
                ('fixed_status', models.IntegerField(default=0)),
            ],
        ),
    ]
