# Generated by Django 4.1 on 2023-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0024_incomeexpence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeexpence',
            name='exin_amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
