# Generated by Django 4.1 on 2023-03-08 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0027_company_holidays_ch_workno'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='emp_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='emp_othe_head',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='emp_other_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='empfull_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='emphalf_leave',
            field=models.IntegerField(default=0),
        ),
    ]
