# Generated by Django 4.1 on 2023-08-11 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0027_company_holidays_ch_workno'),
    ]

    operations = [
        
        
    ]
