# Generated by Django 4.1 on 2023-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0028_receipt_data_register_state_delete_expence_details_and_more'),
    ]

    operations = [
       
    ]
