# Generated by Django 4.1 on 2023-03-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0028_employeesalary_emp_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='emp_delay_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='empfull_leave_amt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='employeesalary',
            name='emphalf_leave_amt',
            field=models.IntegerField(default=0),
        ),
    ]
