# Generated by Django 4.1 on 2023-03-08 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0029_employeesalary_emp_delay_amt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalary',
            name='emp_other_damt',
            field=models.IntegerField(default=0),
        ),
    ]
