# Generated by Django 4.1 on 2023-08-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0029_receipt_data_delete_expence_details_and_more'),
    ]

    operations = [
       
        
       
    ]
