# Generated by Django 4.1 on 2023-03-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0030_employeesalary_emp_other_damt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_fullname', models.CharField(max_length=255)),
                ('auth_signature', models.FileField(upload_to='Receipt')),
                ('company_name', models.CharField(default='', max_length=200)),
                ('company_address1', models.CharField(default='', max_length=200)),
                ('company_address2', models.CharField(default='', max_length=200)),
                ('company_address3', models.CharField(default='', max_length=200)),
                ('company_logo', models.FileField(upload_to='Receipt')),
                ('company_email', models.CharField(default='', max_length=200)),
                ('company_site', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Expence_Details',
        ),
    ]
