# Generated by Django 4.1 on 2023-08-11 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0030_receipt_data_register_state_delete_expence_details_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='employeeregister',
            name='empconfirmsalary',
            field=models.IntegerField(default=0, null=True),
        ),
       
    ]
