# Generated by Django 4.1 on 2023-08-13 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0030_dashboard_register_receipt_data_register_state_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='register_state',
            name='allocateid',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.employeeregister'),
        ),
       
    ]
