# Generated by Django 4.1 on 2023-03-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0031_receipt_data_delete_expence_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt_data',
            name='company_seal',
            field=models.FileField(default='', upload_to='Receipt'),
        ),
        migrations.AlterField(
            model_name='receipt_data',
            name='auth_signature',
            field=models.FileField(default='', upload_to='Receipt'),
        ),
        migrations.AlterField(
            model_name='receipt_data',
            name='company_logo',
            field=models.FileField(default='', upload_to='Receipt'),
        ),
    ]
