# Generated by Django 4.1 on 2023-08-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0032_receipt_data_delete_expence_details_and_more'),
    ]

    operations = [
       
        migrations.AlterField(
            model_name='dashboard_register',
            name='dsh_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        
    ]
