# Generated by Django 4.1 on 2023-08-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0032_dashboard_register_receipt_data_register_state_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='dashboard_register',
            name='active_status',
            field=models.IntegerField(default=0),
        ),
       
    ]
