# Generated by Django 4.1 on 2023-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0032_receipt_data_company_seal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fixed_intial_amt',
            field=models.IntegerField(default=0),
        ),
    ]
