# Generated by Django 4.1 on 2023-08-14 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0033_receipt_data_delete_expence_details_and_more'),
    ]

    operations = [
       
        migrations.AddField(
            model_name='register',
            name='reg_state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state'),
        ),
       
    ]
