# Generated by Django 4.1 on 2023-08-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0035_receipt_data_delete_expence_details_and_more'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='company_holidays',
            name='ch_state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state'),
        ),
       
        migrations.AddField(
            model_name='fixedexpence',
            name='fixed_state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state'),
        ),
        migrations.AddField(
            model_name='incomeexpence',
            name='exin_state',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='payment_app.register_state'),
        ),
       
    ]
